In [1]:
import numpy as np

Question:

Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:

a. Find the distances between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset. Append the newly calculated distances as new column with the given dataset.

b. Given any data point, generate 3 closest neighbors from it.


In [2]:
# step 1 : make a matrix of size (1000000, 2) randomly
matrix = np.random.rand(1000000,2)

In [3]:
matrix, matrix.shape

(array([[0.89848078, 0.8470764 ],
        [0.63283098, 0.38660445],
        [0.51827758, 0.92014529],
        ...,
        [0.58986552, 0.63272241],
        [0.68730844, 0.70769151],
        [0.5212735 , 0.01547635]]),
 (1000000, 2))

In [4]:
# step 2 : find the centroid of the data (mean)

# mean_x = np.mean(matrix[0])
# mean_y = np.mean(matrix[1])

# mean_x, mean_y
centroid = np.mean(matrix, axis = 0)
centroid



array([0.49975451, 0.49965713])

In [5]:
%%time
# step 3 : compute the distance between 2d datapoints and centroid(** Numpy broadcasting)
distance = np.sqrt(np.sum((matrix-centroid)**2, axis = 1)) # axis = 1 is across row 

Wall time: 54.1 ms


In [6]:
distance.shape

(1000000,)

In [7]:
# step 4: add the distance as a new column to our matrix
np.hstack([matrix, distance.reshape(-1,1)])

array([[0.89848078, 0.8470764 , 0.52885044],
       [0.63283098, 0.38660445, 0.17461459],
       [0.51827758, 0.92014529, 0.42089595],
       ...,
       [0.58986552, 0.63272241, 0.16070583],
       [0.68730844, 0.70769151, 0.2800978 ],
       [0.5212735 , 0.01547635, 0.48465874]])

In [8]:
# b. Given any data point, generate 3 closest neighbors from it.

In [9]:
%%time
test = np.random.rand(1,2)
# Calculate distance between test data and all points in matrix
distances = np.sqrt(np.sum((test - matrix)**2, axis = 1))
# sort the array using arg partition and keep only 3 elements
n = 3
min_indices = np.argpartition(distances,n-1)[:n]

Wall time: 74 ms


In [10]:
min_indices

array([503992, 886750, 548216], dtype=int64)

In [11]:
# minimum distances 
distances[min_indices]

array([0.00044938, 0.00047589, 0.00048794])

In [12]:
# points at minimum distance:
matrix[min_indices]

array([[0.40021185, 0.14332855],
       [0.40038379, 0.14337108],
       [0.39963862, 0.14382939]])