In [1]:
import numpy as np

Question:

Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:

a. Find the distances between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset. Append the newly calculated distances as new column with the given dataset.

b. Given any data point, generate 3 closest neighbors from it.


In [11]:
# step 1 : make a matrix of size (1000000, 2) randomly
matrix = np.random.rand(1000000,2)

In [17]:
matrix, matrix.shape

(array([[0.86421295, 0.33054375],
        [0.62803417, 0.65069352],
        [0.15415485, 0.88816077],
        ...,
        [0.78009449, 0.51746051],
        [0.08175391, 0.99104729],
        [0.73412319, 0.7299869 ]]),
 (1000000, 2))

In [22]:
# step 2 : find the centroid of the data (mean)

# mean_x = np.mean(matrix[0])
# mean_y = np.mean(matrix[1])

# mean_x, mean_y
centroid = np.mean(matrix, axis = 0)
centroid



array([0.49952995, 0.50051897])

In [29]:
%%time
# step 3 : compute the distance between 2d datapoints and centroid(** Numpy broadcasting)
distance = np.sqrt(np.sum((matrix-centroid)**2, axis = 1)) # axis = 1 is across row 

CPU times: total: 46.9 ms
Wall time: 49 ms


In [31]:
distance.shape

(1000000,)

In [32]:
# step 4: add the distnace as a new column to our matrix
np.hstack([matrix, distance.reshape(-1,1)])

array([[0.86421295, 0.33054375, 0.40234969],
       [0.62803417, 0.65069352, 0.19765053],
       [0.15415485, 0.88816077, 0.51918217],
       ...,
       [0.78009449, 0.51746051, 0.28107557],
       [0.08175391, 0.99104729, 0.64432511],
       [0.73412319, 0.7299869 , 0.32816081]])

In [33]:
# b. Given any data point, generate 3 closest neighbors from it.

In [60]:
test = np.random.rand(1,2)
# Calculate distance between test data and all points in matrix
distances = np.sqrt(np.sum((test - matrix)**2, axis = 1))
n = 3
min_indices = np.argpartition(distances,n-1)[:n]

In [66]:
min_indices

0.00019151319420720095

In [63]:
# minimum distances 
distances[min_indices]

array([0.00019151, 0.00092959, 0.00104074])

In [64]:
# points at minimum distance:
matrix[min_indices]

array([[0.10208448, 0.02332606],
       [0.1029156 , 0.02325097],
       [0.10107549, 0.02266337]])